version: '3.8'
services:
  app:
    image: php:8.0-apache
    container_name: laravel-app
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 8000:8000
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    ports:
     - 5432:5432
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
     - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@tickets.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - laravel

volumes:
  db_data:
  pgadmin-data:

networks:
  laravel:
